# Generated by Django 5.0.2 on 2024-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Aldohr', models.BooleanField(default=False)),
                ('Al3asr', models.BooleanField(default=False)),
                ('Almaghrib', models.BooleanField(default=False)),
                ('Al3esha', models.BooleanField(default=False)),
                ('daily_quraan', models.BooleanField(default=False)),
                ('tasbee7', models.BooleanField(default=False)),
                ('the_thousand_pray', models.BooleanField(default=False)),
                ('Alfajr', models.BooleanField(default=False)),
            ],
        ),
    ]
