# Generated by Django 5.0.2 on 2024-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('done_or_not', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='alsonan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
