# Generated by Django 5.0.2 on 2024-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('done_or_not', '0003_alter_day_al3asr_alter_day_al3esha_alter_day_aldohr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='Al3asr',
            field=models.CharField(choices=[('Yes in mosque', 'Done in mosque'), ('Yes/no mosque', 'Done but not in mosque'), ('Yes/no mosque + late', 'Done but not in mosque and late'), ("Yes/no mosque + qada'", "Done but qada'"), ('NO', "Wasn't done")], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='Al3esha',
            field=models.CharField(choices=[('Yes in mosque', 'Done in mosque'), ('Yes/no mosque', 'Done but not in mosque'), ('Yes/no mosque + late', 'Done but not in mosque and late'), ("Yes/no mosque + qada'", "Done but qada'"), ('NO', "Wasn't done")], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='Aldohr',
            field=models.CharField(choices=[('Yes in mosque', 'Done in mosque'), ('Yes/no mosque', 'Done but not in mosque'), ('Yes/no mosque + late', 'Done but not in mosque and late'), ("Yes/no mosque + qada'", "Done but qada'"), ('NO', "Wasn't done")], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='Alfajr',
            field=models.CharField(choices=[('Yes in mosque', 'Done in mosque'), ('Yes/no mosque', 'Done but not in mosque'), ('Yes/no mosque + late', 'Done but not in mosque and late'), ("Yes/no mosque + qada'", "Done but qada'"), ('NO', "Wasn't done")], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='Almaghrib',
            field=models.CharField(choices=[('Yes in mosque', 'Done in mosque'), ('Yes/no mosque', 'Done but not in mosque'), ('Yes/no mosque + late', 'Done but not in mosque and late'), ("Yes/no mosque + qada'", "Done but qada'"), ('NO', "Wasn't done")], max_length=70, null=True),
        ),
    ]
